spring:
  application: 
    name: bajoobang
  servlet: 
    multipart: 
      max-file-size: 50MB
      max-request-size: 50MB
  jpa: 
    hibernate: 
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:none}
    properties: 
      hibernate: 
        format_sql: true
    show-sql: ${SPRING_JPA_SHOW_SQL:false}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/bajoobang}"
    username: "${SPRING_DATASOURCE_USERNAME:root}"
    password: "${SPRING_DATASOURCE_PASSWORD:}"
    
server:
  port: ${SERVER_PORT:8080}

app:
  base-url: "${SERVER_BASE_URL:http://localhost:8080}"

file:
  img-dir: "${IMG_DIR:/Users/woosungchoi/study/file/}"

pay: 
  admin-key: "${PAY_ADMIN_KEY}"

geo: 
  api-key: "${GEO_API_KEY}"
  url: "https://dapi.kakao.com/v2/local/search/address.json"